name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.14.0
homepage: https://github.com/SandeepMalviya1999/google_maps_webservice

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  meta: ^1.9.0
  json_annotation: ^4.8.0

dev_dependencies:
  test: ^1.23.1
  pedantic: ^1.11.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  coverage: ^1.6.3
